/**
 * A single editorial word summarizing each surah's central theme, shown on
 * the Surah index list.
 *
 * Unlike the rest of this app's Quran content (Arabic text, translations,
 * tafsir, audio — always fetched from Quran.com), these one-word labels are
 * NOT sourced from any API: there is no single authoritative "theme word"
 * for a surah, so these are this app's own editorial summary, informed by
 * how each surah is commonly introduced in Quranic commentary (tafsir).
 * Treat them as a reading aid, not a scholarly classification — if one
 * looks wrong or could be better, it's a plain content edit to this file,
 * not a data-fetching bug.
 */
export const SURAH_THEMES: Record<number, string> = {
    1: 'Guidance',
    2: 'Covenant',
    3: 'Faith',
    4: 'Justice',
    5: 'Fulfillment',
    6: 'Monotheism',
    7: 'Warning',
    8: 'Victory',
    9: 'Repentance',
    10: 'Patience',
    11: 'Steadfastness',
    12: 'Providence',
    13: 'Thunder',
    14: 'Gratitude',
    15: 'Protection',
    16: 'Blessings',
    17: 'Journey',
    18: 'Trial',
    19: 'Mercy',
    20: 'Reassurance',
    21: 'Prophets',
    22: 'Pilgrimage',
    23: 'Believers',
    24: 'Light',
    25: 'Discernment',
    26: 'Messengers',
    27: 'Ants',
    28: 'Moses',
    29: 'Testing',
    30: 'Prophecy',
    31: 'Wisdom',
    32: 'Prostration',
    33: 'Loyalty',
    34: 'Thankfulness',
    35: 'Creation',
    36: 'Revelation',
    37: 'Angels',
    38: 'Patience',
    39: 'Sincerity',
    40: 'Forgiveness',
    41: 'Clarity',
    42: 'Consultation',
    43: 'Materialism',
    44: 'Smoke',
    45: 'Accountability',
    46: 'Transience',
    47: 'Struggle',
    48: 'Triumph',
    49: 'Etiquette',
    50: 'Omniscience',
    51: 'Sustenance',
    52: 'Certainty',
    53: 'Ascension',
    54: 'Punishment',
    55: 'Mercy',
    56: 'Reckoning',
    57: 'Charity',
    58: 'Pleading',
    59: 'Exile',
    60: 'Allegiance',
    61: 'Ranks',
    62: 'Congregation',
    63: 'Hypocrisy',
    64: 'Deception',
    65: 'Divorce',
    66: 'Prohibition',
    67: 'Sovereignty',
    68: 'Pen',
    69: 'Truth',
    70: 'Prayer',
    71: 'Noah',
    72: 'Jinn',
    73: 'Devotion',
    74: 'Conviction',
    75: 'Resurrection',
    76: 'Generosity',
    77: 'Winds',
    78: 'News',
    79: 'Death',
    80: 'Compassion',
    81: 'Ending',
    82: 'Cleaving',
    83: 'Honesty',
    84: 'Splitting',
    85: 'Persecution',
    86: 'Witness',
    87: 'Purification',
    88: 'Overwhelming',
    89: 'Dawn',
    90: 'Sacrifice',
    91: 'Conscience',
    92: 'Striving',
    93: 'Comfort',
    94: 'Relief',
    95: 'Dignity',
    96: 'Reading',
    97: 'Decree',
    98: 'Evidence',
    99: 'Earthquake',
    100: 'Ingratitude',
    101: 'Catastrophe',
    102: 'Distraction',
    103: 'Time',
    104: 'Slander',
    105: 'Elephant',
    106: 'Provision',
    107: 'Kindness',
    108: 'Abundance',
    109: 'Disbelief',
    110: 'Help',
    111: 'Doom',
    112: 'Oneness',
    113: 'Refuge',
    114: 'Protection',
};

/** The theme word for a surah, or '' if the id is out of range (1-114). */
export function getSurahTheme(chapterId: number): string {
    return SURAH_THEMES[chapterId] ?? '';
}
